version: "0"
services:
  develop:
    image: policy-roles-adapter/dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: policy-roles-adapter-dev
    volumes:
      - .:/app
      - .src:/app
      - ./node_modules:/app
